### ISSUE TITLE
A duplicate line seems to be deletable

### ISSUE THREAD

**Issue by wxdrizzle** [bytedance/kmax-deeplab#1]
Hi, thank you for providing this Pytorch implementation of your great work! I really found it helpful. 

I just show here Line 196 to 199 in `kmax_deeplab/transformer_decoder/kmax_transformer_decoder.py`:
```python
clustering_result = prediction_result['mask_logits'].flatten(2).detach() # line 196
        
    with torch.no_grad():
            clustering_result = prediction_result['mask_logits'].flatten(2).detach() # line 199
```
So, seems that Line 196 can be deleted? Because Line 199 is the same. Thanks in advance!

**Comment by cornettoyu** [comment]
Thanks! You are correct that the two lines were duplicated by mistake. We will update the file accordingly per your suggestions. This should not affect the pre-trained weights and usage of this code repo, thanks!
