### ISSUE TITLE
Can the code be trained on single GPU? (SyncBN)

### ISSUE THREAD

**Issue by yangrongkun** [bytedance/kmax-deeplab#2]
I have tried to train the code on a single GPU, but the SyncBN needs to initialize the distributed training, are there any better method to solve this problem, thank you.

**Comment by cornettoyu** [comment]
Hi,

I think you can change the [SyncBN here](https://github.com/bytedance/kmax-deeplab/blob/main/kmax_deeplab/modeling/pixel_decoder/kmax_pixel_decoder.py#L47) to other normalization layer to replace all SyncBN in the model.

Best,
